### ISSUE TITLE
Unable to pipe stdout cpu-cminer command anymore

### ISSUE THREAD

**Issue by olivierb2** [alephium/cpu-miner#7]
Dear alephium team,

I'm trying to parse the sdtout of cpu-cminer command thanks to a pipe, but it seems not possible while it's working with gpu-command. This is useful to take information to monitoring/statistic server.

How to reproduce

~~~
./cpu-miner  | grep server
~~~

This command should display immediately the following line

~~~
the server is connected 0 0x556791cae890
~~~

But nothing is displayed.

**Comment by polarker** [comment]
> Dear alephium team,
> 
> I'm trying to parse the sdtout of cpu-cminer command thanks to a pipe, but it seems not possible while it's working with gpu-command. This is useful to take information to monitoring/statistic server.
> 
> How to reproduce
> 
> ```
> ./cpu-miner  | grep server
> ```
> 
> This command should display immediately the following line
> 
> ```
> the server is connected 0 0x556791cae890
> ```
> 
> But nothing is displayed.

thanks for the report. I will investigate the issue today

**Comment by polarker** [comment]
@olivierb2 The issue is due to stdout buffer. I pushed a fix to `master` branch, hope it will work for you.

**Comment by olivierb2** [comment]
Dear @polarker ,

Thanks for the update, I confirm it's now all good.

I'm closing this issue.

Best regards.
